# Generated by Django 5.2.3 on 2025-11-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_merge_20250829_2128'),
        ('course', '0007_merge_20250825_1020'),
    ]

    operations = [
    ]
