# Generated by Django 5.2.3 on 2025-11-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_profile_image_alter_customuser_time_zone'),
        ('accounts', '0006_twofactorauth'),
    ]

    operations = [
    ]
