# Generated by Django 5.2.3 on 2025-11-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_merge_20250825_1020'),
        ('assignment', '0007_remove_assignment_batch_remove_assignment_module_and_more'),
    ]

    operations = [
    ]
